# Mongo-Sync Configurations

local:
  db: 'meteor'
  host:
  	port: 3001

remote:
  db: 'ga9rixaX'
  host:
    url: 'waffle.modulusmongo.net'
    port: 27017
  access:
    username: 'gallery_user'
    password: 'oeMhr49cquUg'

# For now :local only accepts DB name and port
# Assumes DB is at localhost:port

# All of the parameters above are required,
# without them, the script will fail
